### ISSUE TITLE
Strange issue with merged directory

### ISSUE THREAD

**Issue by seertenedos** [animosity22/homescripts#47]
Firstly i will state that my setup is a little different than yours because i do it all in docker using shared mounts. I don't think that is the cause but wanted to state it just in case.

I am basically running latest rclone and latest mergerfs using your settings and i am getting something strange from mergerfs.
if i do an "ls" on a directory mounted via rclone directly all is fine but if i do a "ls" on the same directory via the merged mount then close to every second call will list one of the results of "ls" as "No such file or directory" but still show them all in the results. 

I have no idea what is going on and if it would cause an issue for plex or anything using the folders but i was hoping this may have been something you have seen before?

eg
```
ls: /mnt/merged_media/xxx/: No such file or directory
ls: cannot access '/mnt/merged_media/xxx/Season 2': No such file or directory
total 0
drwxr-xr-x 1 root root 0 Jun  3 06:17 'Season 1'
d????????? ? ?    ?    ?            ? 'Season 2'
```
The next call will likely be fine and the one after that will say either Season 1 or Season 2 is misisng normally

**Comment by animosity22** [comment]
I don't use dockers and you don't have any info on your mergerfs setup. You'd have to share more info.

**Comment by Dulanic** [comment]
Try setting  --attr-timeout duration /w rclone. Try 60s or even 1s.

` --attr-timeout 1s`

**Comment by seertenedos** [comment]
Thanks I will try that @Dulanic 
So far i have tried mergerfs version 2.30.0 and 2.29.0
setup is
```
  mergerfs_media:
    container_name: mergerfs_media
    image: hotio/mergerfs:stable-2.29.0
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse
    command: -o rw,use_ino,allow_other,func.getattr=newest,category.action=all,category.create=ff,cache.files=auto-full ${DIR_CLOUD_AWAITING_UPLOAD}=RW:${DIR_CLOUD_RCLONE_MOUNTS}=NC /mnt/merged
    volumes:
      - ${DIR_CLOUD_DATA}:${DIR_CLOUD_DATA}:shared
      - ${DIR_CLOUD_MEDIA_MOUNT}:/mnt/merged:shared
```
${DIR_CLOUD_AWAITING_UPLOAD} and ${DIR_CLOUD_RCLONE_MOUNTS} are both in ${DIR_CLOUD_DATA}

Strangely mergerfs results are basically instant where rclone may take a little longer

**Comment by seertenedos** [comment]
Also i thought i should post my current rclone setup.
v1.53.1
```
rclone_anime:
    container_name: rclone_anime
    image: mumiehub/rclone-mount:latest
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse
    environment:
      - 'MountPoint=/drive'
      - 'RemotePath=anime_crypt:'
      - 'RCLONE_DRIVE_SERVICE_ACCOUNT_FILE=/service_accounts/261.json'
      - 'MountCommands=--allow-other --vfs-cache-max-size 500G --vfs-cache-max-age 336h --dir-cache-time 1000h --log-level INFO --log-file /cache/logs/rclone.log  --poll-interval 15s --umask=000 --dir-perms 0777 --file-perms 0777 --user-agent gjsafqwknvfwtg --cache-dir /cache --vfs-cache-mode full'
      - 'ConfigName=rclone.conf'
    volumes:
      - ./rclone_config:/config
      - ./service_accounts/ForRclone:/service_accounts
      - ${DIR_CLOUD_RCLONE_MOUNTS}/anime:/drive:shared
      - ${DIR_CLOUD_RCLONE_CACHE}/anime:/cache:shared
```
