### ISSUE TITLE
Wireguard instead of OpenVPN?

### ISSUE THREAD

**Issue by rammellzee** [animosity22/homescripts#50]
Since Torguard now supports Wireguard have you considered moving on from OpenVPN?

**Comment by arbitrarypunter** [comment]
I have recently moved my Mullvad VPN from OpenVPN to Wireguard. Server has a symmetric 1Gbps connection and the throughput ont he VPN has went form about 350-450Mbps to pretty much line speed and using far less CPU to achieve that. So was well worth doing for me.
I did have Transmission/OpenVPN setup as per animosity22's instructions for OpenVPN, but for the life of me i couldn't get the routing to work with Wireguard. So i had to use Namespaces and run Transmission and the Wireguard client within a separate Network Namespace to achieve the split tunneling on a per application basis. Happy to share the scripts/config i used if it would be of use.

**Comment by animosity22** [comment]
Thanks for the heads up. I'll take a look at it and see what changes I need to make.

**Comment by Dulanic** [comment]
Here is what I use for my wireguard, it may an option. You need to access your containers running through it by the wireguard container. Hope this helps get you in the right direction.

```

 wireguard:
    image: linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    env_file:
      - ./envs/main.env
    volumes:
      - ./wireguard:/config
      - /lib/modules:/lib/modules
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8089:8089
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
```

I use caddy and this is my config:
```
https://qbittorrent.domain.com {
  import tlscf
  import logs
  @NoAccess not path /api*
  basicauth @NoAccess {
    {$XAUTH}
  }
  reverse_proxy wireguard:8089 {
    header_up X-Forwarded-Host {host}:8089
    header_up -Origin
    header_up -Referer
  } 
}
```

The LSIO wireguard container explains how to add routes for traffic, but this is my wg0.conf additions:
```
PostUp = DROUTE=$(ip route | grep default | awk '{print $3}'); HOMENET=192.168.0.0/16; HOMENET2=10.0.0.0/8; HOMENET3=172.16.0.0/12; ip route add $HOMENET3 via $DROUTE;ip route add $HOMENET2 via $DROUTE; ip route add $HOMENET via $DROUTE;iptables -I OUTPUT -d $HOMENET -j ACCEPT;iptables -A OUTPUT -d $HOMENET2 -j ACCEPT; iptables -A OUTPUT -d $HOMENET3 -j ACCEPT;  iptables -A OUTPUT ! -o %i -m mark ! --mark $(wg show %i fwmark) -m addrtype ! --dst-type LOCAL -j REJECT
PreDown = iptables -D OUTPUT ! -o %i -m mark ! --mark $(wg show %i fwmark) -m addrtype ! --dst-type LOCAL -j REJECT && ip6tables -D OUTPUT ! -o %i -m mark ! --mark $(wg show %i fwmark) -m addrtype ! --dst-type LOCAL -j REJECT
```

**Comment by animosity22** [comment]
I don't use any containers in my setups as it adds a bit of unneeded complexity and no benefit for me.

I was looking at Wireguard and I just don't see how to get Split Tunnel VPN to work yet as that was my old setup with OpenVPN.

**Comment by Dulanic** [comment]
I pay attention lol. I think it's fine with AllowIp setting in the wg.conf.

**Comment by animosity22** [comment]
So my basic setup that's I use is that I stack another IP for my VPN so in my example:

192.168.1.30 is my main IP on my Linux box
192.168.1.31 is my "VPN" ip.

I want to only route 192.168.1.31 so I added 192.168.1.31/32 to my AllowedIPs but that doesn't seem to do it as I see no traffic pass out my wg0 interface from that IP so I have to see what else I'm missing as I see a route for it.

192.168.1.31    0.0.0.0         255.255.255.255 UH        0 0          0 wg0

but doesn't seem to work and split tunnel wireguard doesn't yield much from a working config I could find yet.

**Comment by arbitrarypunter** [comment]
Sounds like you are coming up against similar issues to what i was trying to make this work with wg as i did with openVPN.
The "Table =" in the wg conf file seemed to be where i was getting stuck. Leave it blank and it wanted to send all traffic over the vpn. Set it to off, and no matter what routing/fwmarking magic i tried to weave, i couldn't get any traffic to pass over the VPN.

I got my inspiration for my working setup from: https://gitlab.com/snippets/1919418

Basically i create a New Linux network namespace "wg-transmission", assign a link interface into it. Create another link interface in the root namespace to access it. Then setup the wg connection within wg-transmission namespace and finally start transmission within it.
I then have iptables rules to allow access to transmission on the link interface in its namespace.

Hopefully this gets you going if the namespace option is of interest to you. If not, stop reading now! :-)

Config dumped in here:
https://pastebin.com/QSKRqiKd

That's all a bit rough and ready, and could definitely be streamlined a bit. But it works! Yes, there's added complication having it in a namespace but i learnt a bit along the way putting it in. 
I am kind of hoping someone can show me what routing magic i was missing trying to do the split tunnel the same way you had been by uid/fwmarks, and if they can id go back to that - but nothing i tried worked with WG.

Hope that's of some use to someone.

**Comment by animosity22** [comment]
I think I got it as I found a working method.

So my goal was to stack one IP, 192.168.1.31 on my existing interface and have that IP be the only thing using WG.

Config looks like:

```
# TorGuard WireGuard Config
[Interface]
PrivateKey = PRIVKEY
ListenPort = 51820
Address = 10.13.76.217/24
DNS = 8.8.8.8
Table = off
PostUp = ip rule add from 192.168.1.31 table 42; ip route add default dev %i table 42; iptables -t nat -A POSTROUTING -o %i -j MASQUERADE
PostDown = ip rule del from 192.168.1.31 table 42; iptables -t nat -D POSTROUTING -o %i -j MASQUERADE

[Peer]
PublicKey = PUBKEY
AllowedIPs = 0.0.0.0/0
Endpoint = 67.213.221.19:1443
PersistentKeepalive = 25
```

I bound my qbit to 192.168.1.31 and everything is working like a champ. Just need TG to process my port forward.

**Comment by animosity22** [comment]
Updated to Wireguard and updated the relevant information so this is done.

**Comment by foxswat** [comment]
are there any prerequisites on setting up this "VPN IP" 192.168.1.31 ? 
I tried similar conf but cannot curl from the "VPN IP"

**Comment by animosity22** [comment]
I have a stacked IP on my interface in my netplan like this:

```
root@gemini:/etc/netplan# cat 00-installer-config.yaml
# This is the network config written by 'subiquity'
network:
  ethernets:
    enp5s0:
      addresses:
      - 192.168.1.30/24
      - 192.168.1.31/24
      gateway4: 192.168.1.1
      nameservers:
        addresses:
        - 192.168.1.1
  version: 2
```

and sysctl.conf has:

```
# Torguard VPN
net.ipv4.ip_forward=1
```

and that should do it.
