### ISSUE TITLE
Cache folder is not removing the content after files uploaded to Cloud

### ISSUE THREAD

**Issue by mouzzampk2014** [animosity22/homescripts#91]
Hi @animosity22, apologies its me again but this time different request. 

I am using below variables very similar to yours :) but after files uploaded to the gdrive I can see cache is still not clear. So I read on one of the forum that restarting the rclone will clear the cache (yes cache was cleared after restart) but there must be a better way or automatic. I thought I should check with you if I missed anything from your settings :)

```
    environment:
      - RCLONE_CONFIG=/config/rclone.conf
      - RCLONE_DIR_CACHE_TIME=720h
      - RCLONE_GID=1000
      - RCLONE_TIMEOUT=10m
      - RCLONE_UID=1000
      - RCLONE_UMASK=002
      - RCLONE_VFS_CACHE_MODE=full
      - RCLONE_VFS_CACHE_MAX_SIZE=500G
      - RCLONE_VFS_WRITE_BACK=1h
      - RCLONE_VFS_CACHE_MAX_AGE=720h
      - RCLONE_VFS_READ_AHEAD=1G
    volumes:
      - /mnt/gdrive:/mnt/gdrive:shared
      - /mnt/.config/appdata/rclone:/config
    command: mount "gdrive:"  "/mnt/gdrive" --allow-other --allow-non-empty
```
Thank you
